//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Category_Price = new HashSet<Category_Price>();
            this.ReceiptBasket = new HashSet<ReceiptBasket>();
            this.ReceiptTemplateBasket = new HashSet<ReceiptTemplateBasket>();
            this.PredefinedDiscount = new HashSet<PredefinedDiscount>();
            this.Device_Price = new HashSet<Device_Price>();
            this.Device_TSpotApps_Price = new HashSet<Device_TSpotApps_Price>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sifra { get; set; }
        public string OfferName { get; set; }
    
        public virtual ICollection<Category_Price> Category_Price { get; set; }
        public virtual Contract Contract1 { get; set; }
        public virtual Contract Contract2 { get; set; }
        public virtual ICollection<ReceiptBasket> ReceiptBasket { get; set; }
        public virtual ICollection<ReceiptTemplateBasket> ReceiptTemplateBasket { get; set; }
        public virtual ICollection<PredefinedDiscount> PredefinedDiscount { get; set; }
        public virtual ICollection<Device_Price> Device_Price { get; set; }
        public virtual Device_SelectedContracts Device_SelectedContracts { get; set; }
        public virtual ICollection<Device_TSpotApps_Price> Device_TSpotApps_Price { get; set; }
    }
}
