//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Device_Price = new HashSet<Device_Price>();
            this.Device_TSpotApps_Price = new HashSet<Device_TSpotApps_Price>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string SAP { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberInStock { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StockStateAtDate { get; set; }
        public string Filename { get; set; }
    
        public virtual ICollection<Device_Price> Device_Price { get; set; }
        public virtual ICollection<Device_TSpotApps_Price> Device_TSpotApps_Price { get; set; }
    }
}
