//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Price
    {
        public int device_id { get; set; }
        public int category_id { get; set; }
        public int contract_id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Device Device { get; set; }
    }
}
