//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDbEntities : DbContext
    {
        public LocalDbEntities()
            : base("name=LocalDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WebActionLookup> WebActionLookup { get; set; }
        public DbSet<WebLog> WebLogs { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Geo> Geo { get; set; }
        public DbSet<Receipt> Receipt { get; set; }
        public DbSet<Receipt_ReceiptDetail> Receipt_ReceiptDetail { get; set; }
        public DbSet<ReceiptBasket> ReceiptBasket { get; set; }
        public DbSet<ReceiptDetail> ReceiptDetail { get; set; }
        public DbSet<ReceiptTemplate> ReceiptTemplate { get; set; }
        public DbSet<ReceiptTemplateBasket> ReceiptTemplateBasket { get; set; }
    }
}
