//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedDiscount_Category
    {
        public int predefinedDiscount_id { get; set; }
        public int category_id { get; set; }
        public Nullable<decimal> MonthlyPrice { get; set; }
        public Nullable<decimal> OneTimePrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual PredefinedDiscount PredefinedDiscount { get; set; }
    }
}
