//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptBasket
    {
        public ReceiptBasket()
        {
            this.ReceiptAdditionalOption = new HashSet<ReceiptAdditionalOption>();
        }
    
        public int Id { get; set; }
        public int category_id { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int receipt_id { get; set; }
        public decimal Discount { get; set; }
        public string VrstaRada { get; set; }
        public Nullable<decimal> OneTimeDiscount { get; set; }
        public bool BezOsnovneUsluge { get; set; }
        public bool JednokratnoZaduzenje { get; set; }
        public int contract_id { get; set; }
        public Nullable<int> discount_id { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual ICollection<ReceiptAdditionalOption> ReceiptAdditionalOption { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual PredefinedDiscount PredefinedDiscount { get; set; }
    }
}
