//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.ReceiptBasket = new HashSet<ReceiptBasket>();
        }
    
        public int Id { get; set; }
        public int user_id { get; set; }
        public int geo_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string IP { get; set; }
        public string PdfName { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Geo Geo { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ReceiptBasket> ReceiptBasket { get; set; }
    }
}
