//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptAdditionalOption
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int receiptBasket_id { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool JednokratnoZaduzenje { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual ReceiptBasket ReceiptBasket { get; set; }
    }
}
