//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptTemplate
    {
        public ReceiptTemplate()
        {
            this.ReceiptTemplateBasket = new HashSet<ReceiptTemplateBasket>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ReceiptTemplateBasket> ReceiptTemplateBasket { get; set; }
    }
}
