//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.User = new HashSet<User>();
            this.Category = new HashSet<Category>();
            this.Category_Role_MaxDiscount = new HashSet<Category_Role_MaxDiscount>();
            this.PredefinedDiscount = new HashSet<PredefinedDiscount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool ManagerPrivilages { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<Category_Role_MaxDiscount> Category_Role_MaxDiscount { get; set; }
        public virtual ICollection<PredefinedDiscount> PredefinedDiscount { get; set; }
    }
}
