//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCorpDbEntities : DbContext
    {
        public TCorpDbEntities()
            : base("name=TCorpDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Geo> Geo { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
        public DbSet<ReceiptTemplate> ReceiptTemplate { get; set; }
        public DbSet<ReceiptTemplateBasket> ReceiptTemplateBasket { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<SocketActionLookup> SocketActionLookup { get; set; }
        public DbSet<SocketLog> SocketLog { get; set; }
        public DbSet<SocketUpdate> SocketUpdate { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WebActionLookup> WebActionLookup { get; set; }
        public DbSet<WebLog> WebLogs { get; set; }
        public DbSet<AdditionalOptions> AdditionalOptions { get; set; }
        public DbSet<ReceiptAdditionalOption> ReceiptAdditionalOption { get; set; }
        public DbSet<Category_Role_MaxDiscount> Category_Role_MaxDiscount { get; set; }
        public DbSet<ReceiptDefaultOption> ReceiptDefaultOption { get; set; }
        public DbSet<Category_Price> Category_Price { get; set; }
        public DbSet<Contract> Contract { get; set; }
        public DbSet<ReceiptBasket> ReceiptBasket { get; set; }
        public DbSet<PredefinedDiscount> PredefinedDiscount { get; set; }
        public DbSet<PredefinedDiscount_Category> PredefinedDiscount_Category { get; set; }
        public DbSet<Device> Device { get; set; }
        public DbSet<Device_Price> Device_Price { get; set; }
        public DbSet<Device_SelectedCategories> Device_SelectedCategories { get; set; }
        public DbSet<Device_SelectedContracts> Device_SelectedContracts { get; set; }
        public DbSet<Organization> Organization { get; set; }
        public DbSet<Category_InStock> Category_InStock { get; set; }
        public DbSet<Device_TSpotApps_Price> Device_TSpotApps_Price { get; set; }
        public DbSet<Device_TSpotApps_SelectedCategories> Device_TSpotApps_SelectedCategories { get; set; }
    }
}
