//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Receipt = new HashSet<Receipt>();
            this.ReceiptTemplate = new HashSet<ReceiptTemplate>();
            this.SocketLog = new HashSet<SocketLog>();
            this.WebLog = new HashSet<WebLog>();
            this.Client = new HashSet<Client>();
            this.Subordinates = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public bool IsBanned { get; set; }
        public Nullable<System.DateTime> LastLoginRequest { get; set; }
        public byte FailedLoginAttempts { get; set; }
        public int role_id { get; set; }
        public string Phone { get; set; }
        public string Cellphone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string KPNumber { get; set; }
        public string OIB { get; set; }
        public Nullable<int> superiorUser_id { get; set; }
        public Nullable<System.DateTime> RequestChangeDate { get; set; }
        public string Salt { get; set; }
        public int organization_id { get; set; }
        public string BccField { get; set; }
    
        public virtual ICollection<Receipt> Receipt { get; set; }
        public virtual ICollection<ReceiptTemplate> ReceiptTemplate { get; set; }
        public virtual Role Role { get; set; }
        public virtual Session Session { get; set; }
        public virtual ICollection<SocketLog> SocketLog { get; set; }
        public virtual ICollection<WebLog> WebLog { get; set; }
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<User> Subordinates { get; set; }
        public virtual User Superior { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
