//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCorp.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLog
    {
        public long Id { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> user_id { get; set; }
        public string IP { get; set; }
        public int action_id { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual WebActionLookup WebActionLookup { get; set; }
    }
}
